### ISSUE TITLE
a letter for help

### ISSUE THREAD

**Issue by jeffreyzhang23** [peymanbarca/DeepPos-Simple-indoor-localization#1]
Hi peymanbarca,
  I'm a student studying indoor localization and I'm interested in your  solution based deep learning. Have you published any papers about that? I want to learn it more and it'll be helpful for me to read the code.
  I'm looking forward to your reply. @peymanbarca 
Sincerely,
jeffrey.

**Comment by peymanbarca** [comment]
Hi jeffrey
Thanks for considering the repository,
I'm now a master student and that is my BS project.I'm trying to publish a
journal paper about that as long as it complete.
The code still is a little untidy and readme.md is incomplete. sorry for
that.
And by the way, how can i help you ?

**Comment by jeffreyzhang23** [comment]
Hi peymanbarca,
Thank you for your reply. Looking forward to your journal paper.
Sincerely,
jeffrey.

**Comment by peymanbarca** [comment]
Hi jeffrey
Unfortunately my paper is not ready yet and it probably last long time to
accept in a appropriate journal.
Can I know your degree of student and Why you interested in Indoor
Localization? Is it your project?
regards
Peyman
